### ISSUE TITLE
gradle not working

### ISSUE THREAD

**Issue by sialmo** [pushbit/dining-out#3]
Hi 
I was trying to open this project and gradle shows : Configuration with name 'default' not found.

thanks.

**Comment by pushbit** [comment]
When did you last pull it?  I pushed changes yesterday that should fix that issue.

**Comment by sialmo** [comment]
Thanks for the quick response
actually I did it yesterday :D but now I'm going to download it again
again thanks for response

**Comment by sialmo** [comment]
Hi 
tried it again but still getting errors , this time says:

Could not find com.google.android.gms:play-services-measurement:8.3.0. Required by: dining-out-master:app:unspecified

thanks

**Comment by pushbit** [comment]
Sounds like you need to add Google Repository (and possibly Android Support Repository) in the SDK Manager.

**Comment by sialmo** [comment]
thanks that worked .
now project has been builded but net.sf.diningout.R cannot be resolved.
I cleared the project and rebuilded it but still not work.
again thanks for the response.

**Comment by pushbit** [comment]
Try the 'Sync Project with Gradle Files' button.  If that doesn't work, try a 'Rebuild Project'.

**Comment by sialmo** [comment]
getting this error:
Error:Gradle: Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing from module root folder. The Google Services Plugin cannot function without it.

**Comment by sialmo** [comment]
and still  R file not resolve

**Comment by pushbit** [comment]
It looks like you have the Google Services Plugin enabled for some reason.  Did you create a new project (with all its defaults) and then add dining-out to it?  I wouldn't expect this to be an issue if you import the project directly.

**Comment by sialmo** [comment]
No I just opened the project and the gradle built it.

**Comment by sialmo** [comment]
excuse me for this but yes you were right.
I extracted the zip file again and that issue is gone but now it says:

Error:Android Gradle Build Target: java.lang.NullPointerException

again thank you so much your such a big help

**Comment by sialmo** [comment]
thank you soooo much i figured it out synced it with gradle again and everything is working fine 
thank you.
